version: "3.0"

services:
  # The Forgotten Server
  server:
    build:
      context: forgottenserver
      dockerfile: Dockerfile.clean
    restart: always
    ports:
      - "7171:7171"
      - "7172:7172"
    depends_on:
      - db
    networks:
      - db-network
    volumes:
      - ./orts2/data:/srv/data # Mount world data pack from local copy
      - ./config/config.lua:/srv/config.lua # Mount TFS config file from local copy

  # MyAAC Account Website
  web:
    build:
      context: myaac
    restart: always
    ports:
      - 80:80
    networks:
      - db-network
    depends_on:
      - db
    volumes:
      - ./orts2/data:/srv/data # Mount world data pack from local copy
      - ./config/config.lua:/srv/config.lua # Mount TFS config file from local copy

  # Maria DB
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aibit
      MYSQL_USER: forgottenserver # Also needs to be set in config.lua
      MYSQL_PASSWORD: aibit # Also needs to be set in config.lua
      MYSQL_DATABASE: forgottenserver # Also needs to be set in config.lua
    volumes:
      - ./state/db:/var/lib/mysql # Mount & persist the database storage locally rather than inside the container
      - ./forgottenserver/schema.sql:/docker-entrypoint-initdb.d/forgottenserver_schema.sql # Create TFS database schema on startup
    networks:
      - db-network

  # Optional database admin tool (basically PhpMyAdmin)
  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
