version: "3.0"

services:
  # The Forgotten Server
  server:
    build:
      context: forgottenserver
      dockerfile: Dockerfile.clean
    restart: unless-stopped
    ports:
      - "7171:7171"
      - "7172:7172"
    depends_on:
      - db
    volumes:
      - ./orts2/data:/srv/data # Mount world data pack from local copy
      - ./config/config.lua:/srv/config.lua # Mount TFS config file from local copy

  # MyAAC Account Website
  web:
    build:
      context: myaac
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./orts2/data:/srv/data # Mount world data pack from local copy
      - ./config/config.lua:/srv/config.lua # Mount TFS config file from local copy

  # Maria DB
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: forgottenserver # Also needs to be set in config.lua
      MYSQL_PASSWORD: aibit # Also needs to be set in config.lua
      MYSQL_DATABASE: forgottenserver # Also needs to be set in config.lua
    volumes:
      - ./state/db:/var/lib/mysql # Mount & persist the database storage locally rather than inside the container
      - ./forgottenserver/schema.sql:/docker-entrypoint-initdb.d/forgottenserver_schema.sql # Create TFS database schema on startup
    labels:
      jan-di.database-backup.enable: "true" # Enable automatic database backups
      jan-di.database-backup.username: "forgottenserver" # Username for backup service
      jan-di.database-backup.password: "aibit" # Password for backup service
      jan-di.database-backup.dump_timestamp: "true" # Use timestamp in backup names
      jan-di.database-backup.retention_policy: "simple" # Keep some backups
      jan-di.database-backup.retention_max_count: "60" # Keep two months' worth of backups

  # Optional database admin tool (basically PhpMyAdmin)
  db-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  # Optional automatic database backups
  db-backup:
    image: ghcr.io/jan-di/database-backup:0.3.0
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
      SCHEDULE: "@daily"
      RUN_AT_STARTUP: "true"
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Service needs to read list of running Docker containers
      - ./state/db-backups:/dump # Mount backup directory locally
